# Neural Networks

In this exercise you will learn how to implement a feedforward neural network and train it with backpropagation.

In [1180]:
import numpy as np
from numpy.random import multivariate_normal
from numpy.random import uniform
from scipy.stats import zscore

We define two helper functions "init_toy_data" and "init_model" to create a simple data set to work on and a 2 layer neural network. 

First, we create toy data with categorical labels by sampling from different multivariate normal distributions for each class. 

In [1181]:
def init_toy_data(num_samples,num_features, num_classes, seed=3):
    # num_samples: number of samples *per class*
    # num_features: number of features (excluding bias)
    # num_classes: number of class labels
    # seed: random seed
    np.random.seed(seed)
    X=np.zeros((num_samples*num_classes, num_features))
    y=np.zeros(num_samples*num_classes)
    for c in range(num_classes):
        # initialize multivariate normal distribution for this class:
        # choose a mean for each feature
        means = uniform(low=-10, high=10, size=num_features)
        # choose a variance for each feature
        var = uniform(low=1.0, high=5, size=num_features)
        # for simplicity, all features are uncorrelated (covariance between any two features is 0)
        cov = var * np.eye(num_features)
        # draw samples from normal distribution
        X[c*num_samples:c*num_samples+num_samples,:] = multivariate_normal(means, cov, size=num_samples)
        # set label
        y[c*num_samples:c*num_samples+num_samples] = c
    return X,y


In [1182]:
def init_model(input_size,hidden_size,num_classes, seed=3):
    # input size: number of input features
    # hidden_size: number of units in the hidden layer
    # num_classes: number of class labels, i.e., number of output units
    np.random.seed(seed)
    model = {}
    # initialize weight matrices and biases randomly
    model['W1'] = uniform(low=-1, high=1, size=(input_size, hidden_size))
    model['b1'] = uniform(low=-1, high=1, size=hidden_size)
    model['W2'] = uniform(low=-1, high=1, size=(hidden_size, num_classes))
    model['b2'] = uniform(low=-1, high=1, size=num_classes)
    return model

In [1183]:
# create toy data
X,y= init_toy_data(2,4,3) # 2 samples per class; 4 features, 3 classes
# Normalize data
X = zscore(X, axis=0)
print('X: ' + str(X))
print('y: ' + str(y))

X: [[ 0.39636145  1.09468144 -0.89360845  0.91815536]
 [ 0.94419323 -0.94027869  1.22268078  1.29597409]
 [-1.41577399  1.15477931 -0.62099631  0.08323307]
 [-1.35264614 -0.13598976 -1.14221784  0.26928935]
 [ 0.9352123   0.38225626  1.419864   -1.51152157]
 [ 0.49265316 -1.55544856  0.01427781 -1.0551303 ]]
y: [0. 0. 1. 1. 2. 2.]


We now initialise our neural net with one hidden layer consisting of $10$ units and and an output layer consisting of $3$ units. Here we expect (any number of) training samples with $4$ features. We do not apply any activation functions yet. The following figure shows a graphical representation of this neuronal net. 

<img src="nn.graphviz.png"  width="30%" height="30%">

In [1184]:
# initialize model
model = init_model(input_size=4, hidden_size=10, num_classes=3)

print('model: ' + str(model))
print('model[\'W1\'].shape: ' + str(model['W1'].shape))
print('model[\'W2\'].shape: ' + str(model['W2'].shape))
print('model[\'b1\'].shape: ' + str(model['b1'].shape))
print('model[\'b2\'].shape: ' + str(model['b2'].shape))
print('number of parameters: ' + str((model['W1'].shape[0] * model['W1'].shape[1]) + 
     np.sum(model['W2'].shape[0] * model['W2'].shape[1]) + 
     np.sum(model['b1'].shape[0]) +
     np.sum(model['b2'].shape[0] )))

model: {'W1': array([[ 0.10159581,  0.41629565, -0.41819052,  0.02165521,  0.78589391,
         0.79258618, -0.74882938, -0.58551424, -0.89706559, -0.11838031],
       [-0.94024758, -0.08633355,  0.2982881 , -0.44302543,  0.3525098 ,
         0.18172563, -0.95203624,  0.11770818, -0.48149511, -0.16979761],
       [-0.43294984,  0.38627584, -0.11909256, -0.68626452,  0.08929804,
         0.56062953, -0.38727294, -0.55608423, -0.22405748,  0.8727673 ],
       [ 0.95199084,  0.34476735,  0.80566822,  0.69150174, -0.24401192,
        -0.81556598,  0.30682181,  0.11568152, -0.27687047, -0.54989099]]), 'b1': array([-0.18696017, -0.0621195 , -0.46152884, -0.41641445, -0.0846272 ,
        0.72106783,  0.17250581, -0.43302428, -0.44404499, -0.09075585]), 'W2': array([[-0.58917931, -0.59724258,  0.02807012],
       [-0.82554126, -0.03282894, -0.27564758],
       [ 0.41537324,  0.49349245,  0.38218584],
       [ 0.37836083, -0.25279975,  0.33626961],
       [-0.32030267,  0.14558774, -0.34838568]

<b>Exercise 1</b>: Implement softmax layer.

Implement the softmax function given by 

$softmax(x_i) = \frac{e^{x_i}}{{\sum_{j\in 1...J}e^{x_j}}}$, 

where $J$ is the total number of classes, i.e. the length of  **x** .

Note: Implement the function such that it takes a matrix X of shape (N, J) as input rather than a single instance **x**; N is the number of instances.

In [1185]:
def softmax(X):
    #######################################
    # INSERT YOUR CODE HERE               #
    #######################################
    softmax = []
    for i in range(0,len(X)): #loop through column
        softmax.append([])
        tmp = 0 #temporary variabel to compute denominator
        for j in range(0,len(X[i])): #loop through row
            tmp += np.e**X[i][j] #add to sum
        for j in range(0,len(X[i])): #loop again through row to compute softmax with generated tmp
            softmax[i].append(np.e**X[i][j] / tmp) #append the softmax for cell of iteration
    return np.array(softmax)

Check if everything is correct.

In [1186]:
x = np.array([[0.1, 0.7],[0.7,0.4]])
exact_softmax = np.array([[ 0.35434369,  0.64565631],
                         [ 0.57444252,  0.42555748]])
sm = softmax(x)
difference = np.sum(np.abs(exact_softmax - sm))
try:
    assert difference < 0.000001   
    print("Testing successful.")
except:
    print("Tests failed.")

Testing successful.


<b>Exercise 2</b>: Implement the forward propagation algorithm for the model defined above.

The activation function of the hidden neurons is a Rectified Linear Unit $relu(x)=max(0,x)$ (to be applied element-wise to the hidden units)
The activation function of the output layer is a softmax function as (as implemented in Exercise 1).

The function should return both the activation of the hidden units (after having applied the $relu$ activation function) (shape: $(N, num\_hidden)$) and the softmax model output (shape: $(N, num\_classes)$). 

In [1187]:
def forward_prop(X,model):
    W1=model['W1']
    b1=model['b1']
    W2=model['W2']
    b2=model['b2']
    ###############################################
    # INSERT YOUR CODE HERE                       #
    ###############################################
    probs = np.dot(X,W1) + b1 #apply first weights and first bias on input layer
    hidden_activations = [] #list to collect the hidden activations
    for i in range(0,len(probs)): #loop through row of hidden layer
        hidden_activations.append([])
        for j in range(0,len(probs[i])): #loop through column of hidden layer
            hidden_activations[i].append(max(0,probs[i][j])) #compute relu(x)
    hidden_activations = np.array(hidden_activations) #cast to numpy array
    probs = np.dot(hidden_activations,W2) + b2 #apply second weight and second bias to hidden layer
    probs = softmax(probs) #compute output
    return hidden_activations,probs

In [1188]:
acts,probs = forward_prop(X, model)
correct_probs = np.array([[0.22836388, 0.51816433, 0.25347179],
                            [0.15853289, 0.33057078, 0.51089632],
                            [0.40710319, 0.41765056, 0.17524624],
                            [0.85151353, 0.03656425, 0.11192222],
                            [0.66016592, 0.19839791, 0.14143618],
                            [0.70362036, 0.08667923, 0.20970041]])

# the difference should be very small.
difference =  np.sum(np.abs(probs - correct_probs))

try:
    assert probs.shape==(X.shape[0],len(set(y)))
    assert difference < 0.00001   
    print("Testing successful.")
except:
    print("Tests failed.")

Testing successful.


<b>Exercise 3:</b> 

How would you train the above defined neural network? Which loss-function would you use? You do not need to implement this.

<b>Part 2 (Neural Net using Keras)</b>

Instead of implementing the model learning ourselves, we can use the neural network library Keras for Python (https://keras.io/). Keras is an abstraction layer that either builds on top of Theano or Google's Tensorflow. So please install Keras and Tensorflow/Theano for this lab.

<b>Exercise 4:</b>
    Implement the same model as above using Keras:
    
    ** 1 hidden layer à 10 units
    ** softmax output layer à three units
    ** 4 input features
    
Compile the model using categorical cross-entropy (also referred to as 'softmax-loss') as loss function and using categorical crossentropy together with categorical accuracy as metrics for runtime evaluation during training.

Hint 1: Use the Sequential Class API of Keras (https://keras.io/api/models/sequential/ or https://www.tensorflow.org/guide/keras/sequential_model)

Hint 2: You can use the Adam optimizer of Keras for the model compilation

In [1189]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers.core import Activation

# define the model 
################################################
# INSERT YOUR CODE HERE                        #
################################################
model = Sequential()
hidden_layer = Dense(10,input_shape=(4,)) #define hidden layer with 10 units and 4 input features
output_layer = Dense(3) #define output layer with 3 units
softmax_layer = Activation(activation="softmax") #define softmax on top of the output layer
model.add(hidden_layer) #add hidden layer to the model
model.add(output_layer) #add output layer to the model
model.add(softmax_layer) #add softmax layer to the model


# compile the model
################################################
# INSERT YOUR CODE HERE                        #
################################################
model.compile(optimizer="adam",loss="categorical_crossentropy")

The description of the current network can always be looked at via the summary method. The layers can be accessed via model.layers and weights can be obtained with the method get_weights. Check if your model is as expected. 

In [1190]:
# Check model architecture and initial weights.

W_1, b_1 = model.layers[0].get_weights()
print("First layer weights: %s; shape: %s" % (W_1,W_1.shape))
print("First layer bias: %s; shape: %s" % (b_1,b_1.shape))
W_2, b_2 = model.layers[1].get_weights()
print("Second layer weights: %s; shape: %s" % (W_2,W_2.shape))
print("Second layer bias: %s; shape: %s" % (b_2,b_2.shape))
print("number of layes: " + str(len(model.layers)))
model.summary()


First layer weights: [[ 0.02003604  0.0821476   0.48204148  0.17637426 -0.03980035  0.3142873
  -0.24319637 -0.03022254  0.5806773  -0.22915244]
 [-0.54485744  0.5679556  -0.49870333 -0.02546191  0.5452125   0.2499305
  -0.3062349  -0.38232765  0.5788032   0.5034324 ]
 [-0.13465971  0.33133203  0.48852134  0.12132549  0.42885172  0.19966489
   0.36844587 -0.14712018  0.59116673 -0.51782095]
 [ 0.22869635  0.5383967  -0.6482306   0.5990889  -0.0887602  -0.3819301
  -0.00520873 -0.5908096  -0.06803423 -0.5385958 ]]; shape: (4, 10)
First layer bias: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]; shape: (10,)
Second layer weights: [[-0.37382147  0.44657695  0.36236715]
 [ 0.48784554 -0.54496384 -0.46138775]
 [ 0.09304863  0.28755224 -0.5352305 ]
 [ 0.65812147  0.15202641  0.66281605]
 [ 0.34509063 -0.00986987  0.12270272]
 [ 0.08083677  0.14483106 -0.05168605]
 [-0.26013273 -0.09492815  0.26139206]
 [ 0.3270017   0.6195742   0.05061865]
 [-0.4500135  -0.2675555   0.67798805]
 [ 0.04589635  0.38846457 -0

<b>Exercise 5:</b> Train the model on the toy data set generated below: 

Hints: 

* Keras expects one-hot-coded labels 

* Don't forget to normalize the data

In [1191]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from keras.utils import to_categorical

X, y = init_toy_data(1000,4,3, seed=3)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=67)

##################################
# INSERT YOUR CODE HERE          #
##################################

def normalize(y_pred):
    result = []
    for i in range(0,len(y_pred)): #loop through prediction
        #check which of the 3 categories has the highest value
        if max(y_pred[i]) == y_pred[i][0]:
            result.append([1,0,0]) #model decision is 0
            continue
        if max(y_pred[i]) == y_pred[i][1]:
            result.append([0,1,0]) #model decision is 1
            continue
        if max(y_pred[i]) == y_pred[i][2]:
            result.append([0,0,1]) #model decision is 2
    return np.array(result)

y_train = to_categorical(y_train, 3) #convert to 3 dimensional identity vektor
y_test = to_categorical(y_test, 3) #convert to 3 dimensional identity vektor

model.fit(X_train,y_train) #train model
y_pred = normalize(model.predict(X_test)) #make prediction
print("The accuracy of the trained model is:",accuracy_score(y_true=y_test,y_pred=y_pred)) #display the accuracy of the model

31/31 [==============================] - 0s 567us/step
The accuracy of the trained model is: 0.9424242424242424


Compare the test accuracy with the train accuracy. What can you see? Is the model performing well?